FROM node:alpine
ARG YELP_CONSUMER_KEY
ENV YELP_CONSUMER_KEY ${YELP_CONSUMER_KEY:-0}
ARG YELP_CONSUMER_SECRET
ENV YELP_CONSUMER_SECRET ${YELP_CONSUMER_SECRET:-0}
ARG YELP_TOKEN
ENV YELP_TOKEN ${YELP_TOKEN:-0}
ARG YELP_TOKEN_SECRET
ENV YELP_TOKEN_SECRET ${YELP_TOKEN_SECRET:-0}
ENV PORT=3000
RUN echo $YELP_TOKEN
EXPOSE $PORT
COPY app.js ./
COPY package.json ./
RUN npm install
CMD ["node", "./app.js"]
